navigation_orchestrator:
  ros__parameters:
    # Map saving parameters
    map_path: "/workspace/src/arlab/code/arlab_movement/map/my_map"

    # Adding timestamps to filename
    use_timestamp: false

    amcl_enabled: true
    slam_enabled: true
    nav_enabled: true

    save_to_database: true
    map_topic: "/map"
    database_service: "/arlab/knowledge/add_map"
    database_timeout: 10.0

map_save_publisher:
  ros__parameters:
    # Auto-save interval in seconds (0 = disabled)
    save_interval: 5.0

    # Initial delay before first auto-save
    initial_delay: 0.0
