# ===== Request =====
# Data of the entity to be added
Entity data
---
# ===== Response =====
# ID of the newly added entity
int64 entityid
# Result of the add operation (success/failure with error code)
Result result
