string description
geometry_msgs/Pose pose
string pose_reference_frame
float64 max_picking_force
# Add further pickable specific attributes here
# Time stamp when the entity was last updated
builtin_interfaces/Time stamp
---
#id of the newly added entity
int64 entityid
Result result
