builtin_interfaces/Time max_age_stamp
builtin_interfaces/Time min_age_stamp

# Filter for status_type
StatusType status_type
---
# The list is sorted by time stamps in descending order ("freshest" status first)
RobotStatusEvent[] events
Result result
# Time stamp of the "freshest" event
builtin_interfaces/Time stamp
