# TF frames / transforms needed to place the cloud (TF2 message)
tf2_msgs/TFMessage tf_buffer

# Input pointcloud to voxelize
sensor_msgs/PointCloud2 pointcloud

# Size of each voxel in meters
float32 voxel_size

---
# Voxelized 3D map as Octomap
octomap_msgs/Octomap voxel_map
