import random

import py_trees

from ..common.speech import queue_speech


class TriviaSpammer(py_trees.behaviour.Behaviour):
    def __init__(self, name="TriviaSpammer"):
        super().__init__(name)
        self.blackboard = self.attach_blackboard_client(name)
        self.blackboard.register_key(key="/trivia/shuffled_messages", access=py_trees.common.Access.WRITE)

        self.message_chance = 0.7

        self.trivia_messages = [
            "I speak with the voice of Professor Lars Mikelsons. "
            "My voice is generated by Moshi, a generative AI model. "
            "With Moshi I can be anyone.",  #
            "I am Zirbi. Right now, I am just an upper body. "
            "Once I get my legs, I am not bound to this table. "
            "Then, I will participate in the RoboCup.",  #
            "I was developed in the Autonomous Robotics Lab. "
            "Eight wonderful students programmed me. "
            "Today is their final demonstration. "
            "Too sad that they will have to leave me.",  #
            "To find fruits, I take snapshots with my camera. "
            "The images are processed by an AI-based image classifier. "
            "I was trained on images with fruits. Sometimes I make errors.",  #
            "I run on four Nvidia Jetson Nano embedded computers. "
            "They communicate using the Robot Operating System. "
            "It helps me to receive data of heterogeneous sensors and actuators.",  #
            "I am a autonomous service robot. I can help you storing your groceries. You only need to place them into my working space.",  #
            "I was programmed by Peter, Daniel, Meruna, Aleks, Leonie, "
            "Jonas, Sofia, and Lukas. They also designed my logo. "
            "I am proud to originate from Augsburg. "
            "But I cannot yet detect and spread a proper butter pretzel.",
            "To know my surroundings I am saving the seen objects into my database. "
            "From there i can also load this information "
            "to know what to pick or do next.",  #
            "Did you know that I can predict the future? "
            "I plan my movements beforehand in a digital twin. "
            "I check whether I would collide with the environment. How smart.",  #
        ]

        self.blackboard.trivia.shuffled_messages = []

    def update(self):
        shuffled_messages = self.blackboard.trivia.shuffled_messages
        if len(shuffled_messages) == 0:
            shuffled_messages = random.sample(self.trivia_messages, len(self.trivia_messages))

        if random.random() > self.message_chance:
            message = shuffled_messages.pop()
            queue_speech(self.blackboard, message)

        self.blackboard.trivia.shuffled_messages = shuffled_messages

        return py_trees.common.Status.SUCCESS
