<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arlab_computer_vision</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="aleksander1.michalak@uni-a.de">Aleksander Michalak</maintainer>
  <maintainer email="m.yugarajah@gmail.com">Meruna Yugarajah</maintainer>
  <license>MIT</license>

  <depend>action_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>arlab_knowledge_interfaces</depend>
  <depend>arlab_common_interfaces</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
