# Possible object_name tags
string OBJECT_NAME_UNKNOWN = "object_name_unknown"
string OBJECT_NAME_APPLE = "apple"
string OBJECT_NAME_BANANA = "banana"
string OBJECT_NAME_BEER = "beer"
string OBJECT_NAME_BOTTLE = "bottle"
string OBJECT_NAME_CEREALS = "cereals"
string OBJECT_NAME_CUP = "cup"
string OBJECT_NAME_MILK = "milk"
string OBJECT_NAME_CHIPSCAN = "chipscan"
string OBJECT_NAME_CHIPSBAG = "chipsbag"
string OBJECT_NAME_SHOPPINGBAG = "shoppingbag"

# Possible object_category tags
string OBJECT_CATEGORY_UNKNOWN = "object_category_unknown"
string OBJECT_CATEGORY_SPHERE = "sphere"
string OBJECT_CATEGORY_CUBE = "cube"
string OBJECT_CATEGORY_CYLINDER = "cylinder"
string OBJECT_CATEGORY_CONE = "cone"
string OBJECT_CATEGORY_RING = "ring"
string OBJECT_CATEGORY_CAPSULE = "capsule"

# Tags to calculate picking force
string object_name
string object_category

# Add further pickable specific attributes here
