# Furniture-specific attributes

# Attributes for a table (valid if entity_type == table)
EntityFurnitureTable table

# Attributes for a shelf (valid if entity_type == shelf)
EntityFurnitureShelf shelf

# Attributes for a door (valid if entity_type == door)
EntityFurnitureDoor door

# Attributes for a cupboard (valid if entity_type == cupboard)
EntityFurnitureCupboard cupboard

# Attributes for a dishwasher (valid if entity_type == dishwasher)
EntityFurnitureDishwasher dishwasher

# Attributes for a washer (valid if entity_type == washer)
EntityFurnitureWasher washer

#Attributes for a laundry basket (valid if entity_type == laundry_basket)
EntityFurnitureLaundryBasket laundry_basket

# Attributes for a trash bin (valid if entity_type == trash_bin)
EntityFurnitureTrashBin trash_bin
