# Possible tags
string TAG_UNKNOWN = "unknown"
string TAG_APPLE = "apple"
string TAG_BANANA = "banana"
string TAG_BEER = "beer"
string TAG_BOTTLE = "bottle"
string TAG_CEREALS = "cereals"
string TAG_CUP = "cup"
string TAG_MILK = "milk"
string TAG_CHIPSCAN = "chipscan"
string TAG_CHIPSBAG = "chipsbag"
string TAG_SHOPPINGBAG = "shoppingbag"

# Tag to calculate picking force
string picking_tag

# Add further pickable specific attributes here
