name: Linter markdown and code

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
    md-linter:
        name: Lint markdown files
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          # Execute the markdown linter
          - name: Run the markdown linter
            uses: addnab/docker-run-action@v3
            with:
              image: peterdavehello/markdownlint:0.32.2
              options: -v ${{ github.workspace }}:/md
              run: markdownlint .
          # Execute the python linter (runs even when the previous step failed)
          - name: Run Ruff linter
            uses: astral-sh/ruff-action@v3
